export const REDIRECT_URL = "https://appr.tc";

export const LOOPBACK_CLIENT_ID = "LOOPBACK_CLIENT_ID";

export const RESPONSE_ERROR = "ERROR";
export const RESPONSE_ROOM_FULL = "FULL";
export const RESPONSE_UNKNOWN_ROOM = "UNKNOWN_ROOM";
export const RESPONSE_UNKNOWN_CLIENT = "UNKNOWN_CLIENT";
export const RESPONSE_DUPLICATE_CLIENT = "DUPLICATE_CLIENT";
export const RESPONSE_SUCCESS = "SUCCESS";
export const RESPONSE_INVALID_REQUEST = "INVALID_REQUEST";
export const RESPONSE_CONNECT = "RESPONSE_CONNECT";
export const RESPONSE_DISCONNECT = "RESPONSE_DISCONNECT";
